import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className='bg-teal-200 p-16'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='text-6xl'>Hello World!</main>

    </div>
  )
}
